// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Calculator;

var Currency;

var Make;

var DivideOperation;

exports.Calculator = Calculator;
exports.Currency = Currency;
exports.Make = Make;
exports.DivideOperation = DivideOperation;
/* No side effect */
