type t

@module("dinero.js") @val external down: t = "down"
@module("dinero.js") @val external halfAwayFromZero: t = "halfAwayFromZero"
@module("dinero.js") @val external halfDown: t = "halfDown"
@module("dinero.js") @val external halfEven: t = "halfEven"
@module("dinero.js") @val external halfOdd: t = "halfOdd"
@module("dinero.js") @val external halfTowardsZero: t = "halfTowardsZero"
@module("dinero.js") @val external halfUp: t = "halfUp"
@module("dinero.js") @val external up: t = "up"
