// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Zora = require("zora");
var DineroJs = require("dinero.js");
var Currencies = require("@dinero.js/currencies");

Zora.test("Dinero", (function (t) {
        var dineroUsd = function (amount) {
          return DineroJs.dinero({
                      amount: amount,
                      currency: Currencies.USD
                    });
        };
        var oneDollar = dineroUsd(1000);
        t.equal(DineroJs.toSnapshot(oneDollar.create({
                      amount: 3000,
                      currency: Currencies.USD
                    })), {
              amount: 3000,
              currency: Currencies.USD,
              scale: 2
            }, "create");
        t.equal(DineroJs.toSnapshot(oneDollar), {
              amount: 1000,
              currency: Currencies.USD,
              scale: 2
            }, "constructs a Dinero object");
        t.equal(DineroJs.toSnapshot(DineroJs.add(DineroJs.dinero({
                          amount: 100,
                          currency: Currencies.USD
                        }), DineroJs.dinero({
                          amount: 200,
                          currency: Currencies.USD
                        }))), {
              amount: 300,
              currency: Currencies.USD,
              scale: 2
            }, "adds two Dinero correctly");
        t.equal(DineroJs.toSnapshot(DineroJs.multiply(DineroJs.dinero({
                          amount: 100,
                          currency: Currencies.USD
                        }), {
                      amount: 25,
                      scale: 1
                    })), {
              amount: 2500,
              currency: Currencies.USD,
              scale: 3
            }, "multiplies two Dinero with a scaled amount correctly");
        var match = DineroJs.allocate(DineroJs.dinero({
                  amount: 20000,
                  currency: Currencies.USD
                }), [
              1,
              1
            ]);
        t.equal([
              DineroJs.toSnapshot(match[0]),
              DineroJs.toSnapshot(match[1])
            ], [
              DineroJs.toSnapshot(DineroJs.dinero({
                        amount: 10000,
                        currency: Currencies.USD
                      })),
              DineroJs.toSnapshot(DineroJs.dinero({
                        amount: 10000,
                        currency: Currencies.USD
                      }))
            ], "allocates a Dinero evenly");
        t.equal(DineroJs.toSnapshot(DineroJs.multiply(DineroJs.dinero({
                          amount: 100,
                          currency: Currencies.USD
                        }), 2)), {
              amount: 200,
              currency: Currencies.USD,
              scale: 2
            }, "multiplies two Dinero with a number correctly");
        t.equal(DineroJs.toDecimal(DineroJs.dinero({
                      amount: 100,
                      currency: Currencies.USD
                    })), "1.00", "formats a currency correctly");
      }));

/*  Not a pure module */
